### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by gotoprodighy** [ChickenOnYT/MobileDevice-ProdigyHacking#18]
***What items should be in the account?***:all of them 

***What level do you want, how much gold, dark tower floor, etc?***:lvl 100 and bunch of gold and tower lvl 100 can yo get me a member pls 

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:my gmail is mccombs.zachary2007@gmail.com

***Would you like to be subscribed to the https://digitalteal.com mailing list? (yes/no)***:
Yes (default)

**Comment by ChickenOnYT** [comment]
This is currently closed. I've discontinued the project because I'm too busy.
