### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by BETPRODIGYHACKER** [ChickenOnYT/MobileDevice-ProdigyHacking#20]
***What items should be in the account?***:everything

***What level do you want, how much gold, dark tower floor, etc?***:level INFINITY if not 10000 is good  gold 999999999999999999999999999999999999999999 floor 100 

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:THEW124RD@outlook.com

***Would you like to be subscribed to the https://digitalteal.com mailing list? (yes/no)***:no
Yes (default)

**Comment by ChickenOnYT** [comment]
This is currently closed. I've discontinued the project because I'm too busy.
